import { qs } from "./dom";

export const elements = {
  signInBtn: qs<HTMLButtonElement>("#sign-in-btn"),
  signOutBtn: qs<HTMLButtonElement>("#sign-out-btn"),
  authMeta: qs<HTMLDivElement>("#auth-meta"),
  authHint: qs<HTMLElement>("#auth-hint"),
  lists: qs<HTMLUListElement>("#lists"),
  newListBtn: qs<HTMLButtonElement>("#new-list-btn"),
  newListForm: qs<HTMLFormElement>("#new-list-form"),
  newListInput: qs<HTMLInputElement>("#new-list-input"),
  cancelListBtn: qs<HTMLButtonElement>("#cancel-list-btn"),
  editListBtn: qs<HTMLButtonElement>("#edit-list-btn"),
  editListForm: qs<HTMLFormElement>("#edit-list-form"),
  editListInput: qs<HTMLInputElement>("#edit-list-input"),
  cancelEditListBtn: qs<HTMLButtonElement>("#cancel-edit-list-btn"),
  renameListForm: qs<HTMLFormElement>("#rename-list-form"),
  renameListInput: qs<HTMLInputElement>("#rename-list-input"),
  cancelRenameListBtn: qs<HTMLButtonElement>("#cancel-rename-list-btn"),
  checkAllBtn: qs<HTMLButtonElement>("#check-all-btn"),
  uncheckAllBtn: qs<HTMLButtonElement>("#uncheck-all-btn"),
  clearCheckedBtn: qs<HTMLButtonElement>("#clear-checked-btn"),
  clearAllBtn: qs<HTMLButtonElement>("#clear-all-btn"),
  activeListTitle: qs<HTMLHeadingElement>("#active-list-title"),
  activeListSubtitle: qs<HTMLParagraphElement>("#active-list-subtitle"),
  deleteListBtn: qs<HTMLButtonElement>("#delete-list-btn"),
  newItemForm: qs<HTMLFormElement>("#new-item-form"),
  newItemInput: qs<HTMLInputElement>("#new-item-input"),
  items: qs<HTMLUListElement>("#items"),
  deleteDialog: qs<HTMLDialogElement>("#delete-list-dialog"),
  confirmDeleteBtn: qs<HTMLButtonElement>("#confirm-delete-btn"),
  cancelDeleteBtn: qs<HTMLButtonElement>("#cancel-delete-btn"),
};
